tasks:
  - name: Setup Flutter
    init: |
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      export PATH="$PATH:/workspace/flutter/bin"
      flutter doctor
    command: |
      export PATH="$PATH:/workspace/flutter/bin"
      flutter pub get
      flutter run -d web-server --web-port=8080
ports:
  - port: 8080
    onOpen: open-preview
